### PR TITLE
Next

### PR DESCRIPTION
**Pull request by petute**
- **What is the new behavior (if this is a feature change)?**

- Add WeaponShowcase
  - It consists of three Weapons with a title and a description.
  - The Weapons as well as the descriptions have an entry animation.
  - The WeaponShowcase cycles through the weapons automatically every 10 seconds or manually by clicking on the circles below it.

- Add CategoryShowcase
  - Consisting of a Navbar with several tabs which hold six articles each. 
  - There are entry animations coming in from the top or bottom decided by the position of the current to the new tab in the navbar.
  - Also included is a hover animation which scales the article as well as animating a line at the top and bottom of the article.

- Add BulletShowcase
  - Nine svg images of bullet outlines with the corresponding caliber written below it make up the BulletShowcase.
  - In the mobile version it changes into a picture of bullets with the word "Munition" written in its center.
  - The desktop version also sports a svg hover color change.

- Add AccessorieShowcase
  - Just an image with the text accessories written in the middle.
  - Also has an hover shine animation.

image
image

- Add NewsSection. The NewsSection consists of a heading, a teaser text and Cards made out of the NewsPages nested in the IndexPage. The Cards onClick also open an Modal and push a link to the modal into the address bar. To find out how the styling looks view the pictures below.

image
image

- Add FeaturedProductCard. The card includes the information typical for a shop card. It also has a hover effect that both adds a red border on the top and bottom and pushes a sidebar out of the card that includes previews of the other product images. If you click on them the main image is replaced with the chosen image.
- Add FeaturedProductsSection. The section features 8 FeaturedProductCards in a Chakra UI Wrap.

https://user-images.githubusercontent.com/36262190/145692398-fcba8cb3-f0d6-4ef3-bb8e-90fd7fc04cbe.mp4

- Add ReviewCard. The Card consists of a text (limited to 5 lines), an avatar image, the rating and the name of the reviewer. OnClick the Card opens a Modal which shows the full text and again the rating and the name. There also is a link pushed to the address bar onClick.
- Add ReviewSection. The Section consists of up to ten ReviewCards in a Flex at max 4 at a time. One can navigate through the cards by clicking the chevrons to the left and right.
- Modify gatsby-node.js. Fetch google review data with the help of the scale serp api. 125 builds a month are free.

image
image

- Add AboutSection. The section consists of a heading, a subheading and a text on the left side and an image that is surrounded by linear gradients to the right.

image

### CODE REVIEW

**Comment by schettn** [comment]
Outcomes of the meeting on december 12th.

@kleberbaum @petute 

# Additions:
  - [ ] PartnerSection
  - [ ] Waffenführerschein Section
    - [ ] Kontaktformular für Waffenführerschein Section
  - [ ] Navbar
  - [ ] Footer

# Fixes:
 - [ ] Overflow-x --> FeaturedProductsSection?
 - [ ] border radius 5px
## Hero
  - [ ] WeaponShowcase tab hover
  - [ ] BackgroundImage weird on resize (strg + '+')
  - [ ] Page scrolls down on doubleclick on dot
  - [ ] WeaponTab more structured (kaliber always in same position)
  - [ ] Price in WeaponTab
  - [ ] Buttons wrong select color (outline)
  - [ ] Button hover animation --> pointer
  - [ ] AcessoriesText not selectable
  - [ ] Acessorie- and BulletShowcase pictures
  - [ ] WeaponShowcase no select
  - [ ] Test animations on mobile (Hover)
 ## News
  - [ ] Mobile gestures
  - [ ] No title no teaser
  - [ ] Arrows on large devices closer to border
  - [ ] Arrows from appleshop https://www.apple.com/at/store
  - [ ] more spacing in cards
  - [ ] cards larger
  - [ ] in Modal left right?
  - [ ] on Modal close close share
  - [ ] modal scrollable on smaller heights
  - [ ] modal vertical center
  - [ ] Modal like instagram?
  - [ ] Heading too large
  - [ ] Restyle cards more like  (template)[https://chakra-templates.dev/templates/components/cards/blogPostWithImage]
 ## Product
  - [ ] like https://chakra-templates.dev/templates/components/cards/productAddToCart
  - [ ] Hover border pixel error --> border over whole container?
  - [ ] Change pictures from preview to change with middle picture on hover
  - [ ] onClick product card
  - [ ] delay on hover + fade
 ## Review
  - [ ] smaller user avatars
  - [ ] author from blog page (template)[https://chakra-templates.dev/templates/components/cards/blogPostWithImage]
  - [ ] Mehr lesen link instead of button
 ## About
  - [ ] Text padding left

**Review by schettn — CHANGES_REQUESTED** [review]
Have a look.
BTW: Your inline css definitions are a little bit strange. But: we will leave it as it is for now.

**Comment by schettn** [comment]
Outcomes of the meeting on december 20th:

- [ ] remove userSelect from unnecessary places
- [x] fallback Image prop

- FeaturedProductSection
  - [x] ShoppingCart Hover
  - [ ] Improve Card

- ReviewSection
  - [x] UserReview left Button (instead of link) right
  - [x] truncate name

- HeroSection
  - [x] If price and kaliber too long buggy
  - [x] Reduced price WeaponTab
  - [x] New dot right corner (like below)

- NewsSection
  - [x] Modal width - 20%
  - [x] Tag in Modal
  - [x] Design Line after CardHeading (divider)
  - [x] Pointer & hover (red arrow, circle darker) on arrows 
--> only circle darker

- LicenseSection --> FAQSection
  - [x] Selector Request type
  - [x] + TextArea
  - [x] No Age
  - [x] Agb Hakerl + text
  - [x] Section dark
  - [x] Box around "Jetzt Anfragen" --> lighter bg

**Review by schettn — APPROVED** [review]
lgtm

**Review by kleberbaum — APPROVED** [review]
lgtm

**Pull request merged**
